version: '3.9'

services:
    tigase-xmpp-server:
        container_name: xmpp
        hostname: xmpp
        image: tigase/tigase-xmpp-server:latest
        restart: always
        ports:
            - '5222:5222'
            - '8080:8080'
